name: MC-Seasons-Skyblock
description:
version: 1.0.0
author: AlexanderNL_
main: me.msc.skyblock.Main
commands:
  fly:
    description: Toggle Fly mode
    usage: /<command>
  playerstate:
    description: Check player state
    usage: /<command>
  spawn:
    description: Go to the spawn
    usage: /<command>
  setspawn:
    description: Set a new spawn location
    usage: /<command>
  updateprefix:
    description: Set a new prefix for a player
    usage: /<command> <player> <prefix>
  craft:
    description: Craft something
    usage: /<command>